### ISSUE TITLE
react-app-rewired: not found error when trying to build dev

### ISSUE THREAD

**Issue by schristley** [fairspace/workspace#1443]
I'm following the docs to get a local development instance running but getting this error when doing `yarn dev` in `projects/mercury`. I guess `react-app-rewired` is a node package but not sure, is there some prerequisite I'm missing?

I'm on ubuntu 22.04, with nodejs v20.10.0 and yarn 1.22.21.

here's the raw output
```
$ yarn dev
yarn run v1.22.21
$ yarn build && concurrently "yarn localdevelopment" "yarn saturn" "yarn pluto" "yarn start"
$ react-app-rewired build
/bin/sh: 1: react-app-rewired: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tgreenwood** [comment]
Hi @schristley ,

try to execute

**Comment by tgreenwood** [comment]
Hi @schristley ,

try to execute 
`yarn install`
for the first run to install all dependencies to your local node_modules dir.

Please, let me know if it does not resolve the issue.

UPD: will update the README shortly

**Comment by schristley** [comment]
thanks, that worked!
